// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package identity

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Identity                protoreflect.MessageDescriptor
	fd_Identity_id             protoreflect.FieldDescriptor
	fd_Identity_fullName       protoreflect.FieldDescriptor
	fd_Identity_dateOfBirth    protoreflect.FieldDescriptor
	fd_Identity_nationalIdHash protoreflect.FieldDescriptor
	fd_Identity_isVerified     protoreflect.FieldDescriptor
	fd_Identity_verifiedBy     protoreflect.FieldDescriptor
	fd_Identity_createdAt      protoreflect.FieldDescriptor
	fd_Identity_verifiedAt     protoreflect.FieldDescriptor
	fd_Identity_creator        protoreflect.FieldDescriptor
)

func init() {
	file_test_identity_identity_proto_init()
	md_Identity = File_test_identity_identity_proto.Messages().ByName("Identity")
	fd_Identity_id = md_Identity.Fields().ByName("id")
	fd_Identity_fullName = md_Identity.Fields().ByName("fullName")
	fd_Identity_dateOfBirth = md_Identity.Fields().ByName("dateOfBirth")
	fd_Identity_nationalIdHash = md_Identity.Fields().ByName("nationalIdHash")
	fd_Identity_isVerified = md_Identity.Fields().ByName("isVerified")
	fd_Identity_verifiedBy = md_Identity.Fields().ByName("verifiedBy")
	fd_Identity_createdAt = md_Identity.Fields().ByName("createdAt")
	fd_Identity_verifiedAt = md_Identity.Fields().ByName("verifiedAt")
	fd_Identity_creator = md_Identity.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_Identity)(nil)

type fastReflection_Identity Identity

func (x *Identity) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Identity)(x)
}

func (x *Identity) slowProtoReflect() protoreflect.Message {
	mi := &file_test_identity_identity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Identity_messageType fastReflection_Identity_messageType
var _ protoreflect.MessageType = fastReflection_Identity_messageType{}

type fastReflection_Identity_messageType struct{}

func (x fastReflection_Identity_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Identity)(nil)
}
func (x fastReflection_Identity_messageType) New() protoreflect.Message {
	return new(fastReflection_Identity)
}
func (x fastReflection_Identity_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Identity
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Identity) Descriptor() protoreflect.MessageDescriptor {
	return md_Identity
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Identity) Type() protoreflect.MessageType {
	return _fastReflection_Identity_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Identity) New() protoreflect.Message {
	return new(fastReflection_Identity)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Identity) Interface() protoreflect.ProtoMessage {
	return (*Identity)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Identity) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Identity_id, value) {
			return
		}
	}
	if x.FullName != "" {
		value := protoreflect.ValueOfString(x.FullName)
		if !f(fd_Identity_fullName, value) {
			return
		}
	}
	if x.DateOfBirth != "" {
		value := protoreflect.ValueOfString(x.DateOfBirth)
		if !f(fd_Identity_dateOfBirth, value) {
			return
		}
	}
	if x.NationalIdHash != "" {
		value := protoreflect.ValueOfString(x.NationalIdHash)
		if !f(fd_Identity_nationalIdHash, value) {
			return
		}
	}
	if x.IsVerified != false {
		value := protoreflect.ValueOfBool(x.IsVerified)
		if !f(fd_Identity_isVerified, value) {
			return
		}
	}
	if x.VerifiedBy != "" {
		value := protoreflect.ValueOfString(x.VerifiedBy)
		if !f(fd_Identity_verifiedBy, value) {
			return
		}
	}
	if x.CreatedAt != int32(0) {
		value := protoreflect.ValueOfInt32(x.CreatedAt)
		if !f(fd_Identity_createdAt, value) {
			return
		}
	}
	if x.VerifiedAt != int32(0) {
		value := protoreflect.ValueOfInt32(x.VerifiedAt)
		if !f(fd_Identity_verifiedAt, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Identity_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Identity) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "test.identity.Identity.id":
		return x.Id != uint64(0)
	case "test.identity.Identity.fullName":
		return x.FullName != ""
	case "test.identity.Identity.dateOfBirth":
		return x.DateOfBirth != ""
	case "test.identity.Identity.nationalIdHash":
		return x.NationalIdHash != ""
	case "test.identity.Identity.isVerified":
		return x.IsVerified != false
	case "test.identity.Identity.verifiedBy":
		return x.VerifiedBy != ""
	case "test.identity.Identity.createdAt":
		return x.CreatedAt != int32(0)
	case "test.identity.Identity.verifiedAt":
		return x.VerifiedAt != int32(0)
	case "test.identity.Identity.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: test.identity.Identity"))
		}
		panic(fmt.Errorf("message test.identity.Identity does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Identity) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "test.identity.Identity.id":
		x.Id = uint64(0)
	case "test.identity.Identity.fullName":
		x.FullName = ""
	case "test.identity.Identity.dateOfBirth":
		x.DateOfBirth = ""
	case "test.identity.Identity.nationalIdHash":
		x.NationalIdHash = ""
	case "test.identity.Identity.isVerified":
		x.IsVerified = false
	case "test.identity.Identity.verifiedBy":
		x.VerifiedBy = ""
	case "test.identity.Identity.createdAt":
		x.CreatedAt = int32(0)
	case "test.identity.Identity.verifiedAt":
		x.VerifiedAt = int32(0)
	case "test.identity.Identity.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: test.identity.Identity"))
		}
		panic(fmt.Errorf("message test.identity.Identity does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Identity) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "test.identity.Identity.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "test.identity.Identity.fullName":
		value := x.FullName
		return protoreflect.ValueOfString(value)
	case "test.identity.Identity.dateOfBirth":
		value := x.DateOfBirth
		return protoreflect.ValueOfString(value)
	case "test.identity.Identity.nationalIdHash":
		value := x.NationalIdHash
		return protoreflect.ValueOfString(value)
	case "test.identity.Identity.isVerified":
		value := x.IsVerified
		return protoreflect.ValueOfBool(value)
	case "test.identity.Identity.verifiedBy":
		value := x.VerifiedBy
		return protoreflect.ValueOfString(value)
	case "test.identity.Identity.createdAt":
		value := x.CreatedAt
		return protoreflect.ValueOfInt32(value)
	case "test.identity.Identity.verifiedAt":
		value := x.VerifiedAt
		return protoreflect.ValueOfInt32(value)
	case "test.identity.Identity.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: test.identity.Identity"))
		}
		panic(fmt.Errorf("message test.identity.Identity does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Identity) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "test.identity.Identity.id":
		x.Id = value.Uint()
	case "test.identity.Identity.fullName":
		x.FullName = value.Interface().(string)
	case "test.identity.Identity.dateOfBirth":
		x.DateOfBirth = value.Interface().(string)
	case "test.identity.Identity.nationalIdHash":
		x.NationalIdHash = value.Interface().(string)
	case "test.identity.Identity.isVerified":
		x.IsVerified = value.Bool()
	case "test.identity.Identity.verifiedBy":
		x.VerifiedBy = value.Interface().(string)
	case "test.identity.Identity.createdAt":
		x.CreatedAt = int32(value.Int())
	case "test.identity.Identity.verifiedAt":
		x.VerifiedAt = int32(value.Int())
	case "test.identity.Identity.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: test.identity.Identity"))
		}
		panic(fmt.Errorf("message test.identity.Identity does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Identity) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "test.identity.Identity.id":
		panic(fmt.Errorf("field id of message test.identity.Identity is not mutable"))
	case "test.identity.Identity.fullName":
		panic(fmt.Errorf("field fullName of message test.identity.Identity is not mutable"))
	case "test.identity.Identity.dateOfBirth":
		panic(fmt.Errorf("field dateOfBirth of message test.identity.Identity is not mutable"))
	case "test.identity.Identity.nationalIdHash":
		panic(fmt.Errorf("field nationalIdHash of message test.identity.Identity is not mutable"))
	case "test.identity.Identity.isVerified":
		panic(fmt.Errorf("field isVerified of message test.identity.Identity is not mutable"))
	case "test.identity.Identity.verifiedBy":
		panic(fmt.Errorf("field verifiedBy of message test.identity.Identity is not mutable"))
	case "test.identity.Identity.createdAt":
		panic(fmt.Errorf("field createdAt of message test.identity.Identity is not mutable"))
	case "test.identity.Identity.verifiedAt":
		panic(fmt.Errorf("field verifiedAt of message test.identity.Identity is not mutable"))
	case "test.identity.Identity.creator":
		panic(fmt.Errorf("field creator of message test.identity.Identity is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: test.identity.Identity"))
		}
		panic(fmt.Errorf("message test.identity.Identity does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Identity) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "test.identity.Identity.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "test.identity.Identity.fullName":
		return protoreflect.ValueOfString("")
	case "test.identity.Identity.dateOfBirth":
		return protoreflect.ValueOfString("")
	case "test.identity.Identity.nationalIdHash":
		return protoreflect.ValueOfString("")
	case "test.identity.Identity.isVerified":
		return protoreflect.ValueOfBool(false)
	case "test.identity.Identity.verifiedBy":
		return protoreflect.ValueOfString("")
	case "test.identity.Identity.createdAt":
		return protoreflect.ValueOfInt32(int32(0))
	case "test.identity.Identity.verifiedAt":
		return protoreflect.ValueOfInt32(int32(0))
	case "test.identity.Identity.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: test.identity.Identity"))
		}
		panic(fmt.Errorf("message test.identity.Identity does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Identity) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in test.identity.Identity", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Identity) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Identity) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Identity) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Identity) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Identity)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.FullName)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DateOfBirth)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NationalIdHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.IsVerified {
			n += 2
		}
		l = len(x.VerifiedBy)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.CreatedAt != 0 {
			n += 1 + runtime.Sov(uint64(x.CreatedAt))
		}
		if x.VerifiedAt != 0 {
			n += 1 + runtime.Sov(uint64(x.VerifiedAt))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Identity)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x4a
		}
		if x.VerifiedAt != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.VerifiedAt))
			i--
			dAtA[i] = 0x40
		}
		if x.CreatedAt != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CreatedAt))
			i--
			dAtA[i] = 0x38
		}
		if len(x.VerifiedBy) > 0 {
			i -= len(x.VerifiedBy)
			copy(dAtA[i:], x.VerifiedBy)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.VerifiedBy)))
			i--
			dAtA[i] = 0x32
		}
		if x.IsVerified {
			i--
			if x.IsVerified {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x28
		}
		if len(x.NationalIdHash) > 0 {
			i -= len(x.NationalIdHash)
			copy(dAtA[i:], x.NationalIdHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NationalIdHash)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.DateOfBirth) > 0 {
			i -= len(x.DateOfBirth)
			copy(dAtA[i:], x.DateOfBirth)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DateOfBirth)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.FullName) > 0 {
			i -= len(x.FullName)
			copy(dAtA[i:], x.FullName)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.FullName)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Identity)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Identity: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Identity: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FullName", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.FullName = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DateOfBirth", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DateOfBirth = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NationalIdHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NationalIdHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field IsVerified", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.IsVerified = bool(v != 0)
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VerifiedBy", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.VerifiedBy = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
				}
				x.CreatedAt = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CreatedAt |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VerifiedAt", wireType)
				}
				x.VerifiedAt = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.VerifiedAt |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: test/identity/identity.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName       string `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	DateOfBirth    string `protobuf:"bytes,3,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	NationalIdHash string `protobuf:"bytes,4,opt,name=nationalIdHash,proto3" json:"nationalIdHash,omitempty"`
	IsVerified     bool   `protobuf:"varint,5,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	VerifiedBy     string `protobuf:"bytes,6,opt,name=verifiedBy,proto3" json:"verifiedBy,omitempty"`
	CreatedAt      int32  `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	VerifiedAt     int32  `protobuf:"varint,8,opt,name=verifiedAt,proto3" json:"verifiedAt,omitempty"`
	Creator        string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_identity_identity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_test_identity_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Identity) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Identity) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Identity) GetNationalIdHash() string {
	if x != nil {
		return x.NationalIdHash
	}
	return ""
}

func (x *Identity) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Identity) GetVerifiedBy() string {
	if x != nil {
		return x.VerifiedBy
	}
	return ""
}

func (x *Identity) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Identity) GetVerifiedAt() int32 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

func (x *Identity) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_test_identity_identity_proto protoreflect.FileDescriptor

var file_test_identity_identity_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x98, 0x02,
	0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75,
	0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75,
	0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66,
	0x42, 0x69, 0x72, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0xa6, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x0d,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6e, 0x68, 0x50,
	0x68, 0x69, 0x78, 0x33, 0x34, 0x30, 0x35, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0xa2, 0x02,
	0x03, 0x54, 0x49, 0x58, 0xaa, 0x02, 0x0d, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0xca, 0x02, 0x0d, 0x54, 0x65, 0x73, 0x74, 0x5c, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0xe2, 0x02, 0x19, 0x54, 0x65, 0x73, 0x74, 0x5c, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x3a, 0x3a, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_identity_identity_proto_rawDescOnce sync.Once
	file_test_identity_identity_proto_rawDescData = file_test_identity_identity_proto_rawDesc
)

func file_test_identity_identity_proto_rawDescGZIP() []byte {
	file_test_identity_identity_proto_rawDescOnce.Do(func() {
		file_test_identity_identity_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_identity_identity_proto_rawDescData)
	})
	return file_test_identity_identity_proto_rawDescData
}

var file_test_identity_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_identity_identity_proto_goTypes = []interface{}{
	(*Identity)(nil), // 0: test.identity.Identity
}
var file_test_identity_identity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_identity_identity_proto_init() }
func file_test_identity_identity_proto_init() {
	if File_test_identity_identity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_identity_identity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_identity_identity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_identity_identity_proto_goTypes,
		DependencyIndexes: file_test_identity_identity_proto_depIdxs,
		MessageInfos:      file_test_identity_identity_proto_msgTypes,
	}.Build()
	File_test_identity_identity_proto = out.File
	file_test_identity_identity_proto_rawDesc = nil
	file_test_identity_identity_proto_goTypes = nil
	file_test_identity_identity_proto_depIdxs = nil
}
