// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: test/identity/query.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName               = "/test.identity.Query/Params"
	Query_Identity_FullMethodName             = "/test.identity.Query/Identity"
	Query_IdentityAll_FullMethodName          = "/test.identity.Query/IdentityAll"
	Query_IdentityByNationalId_FullMethodName = "/test.identity.Query/IdentityByNationalId"
	Query_IdentityByOwner_FullMethodName      = "/test.identity.Query/IdentityByOwner"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Identity items.
	Identity(ctx context.Context, in *QueryGetIdentityRequest, opts ...grpc.CallOption) (*QueryGetIdentityResponse, error)
	IdentityAll(ctx context.Context, in *QueryAllIdentityRequest, opts ...grpc.CallOption) (*QueryAllIdentityResponse, error)
	// Queries a list of IdentityByNationalId items.
	IdentityByNationalId(ctx context.Context, in *QueryIdentityByNationalIdRequest, opts ...grpc.CallOption) (*QueryIdentityByNationalIdResponse, error)
	// Queries a list of IdentityByOwner items.
	IdentityByOwner(ctx context.Context, in *QueryIdentityByOwnerRequest, opts ...grpc.CallOption) (*QueryIdentityByOwnerResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Identity(ctx context.Context, in *QueryGetIdentityRequest, opts ...grpc.CallOption) (*QueryGetIdentityResponse, error) {
	out := new(QueryGetIdentityResponse)
	err := c.cc.Invoke(ctx, Query_Identity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IdentityAll(ctx context.Context, in *QueryAllIdentityRequest, opts ...grpc.CallOption) (*QueryAllIdentityResponse, error) {
	out := new(QueryAllIdentityResponse)
	err := c.cc.Invoke(ctx, Query_IdentityAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IdentityByNationalId(ctx context.Context, in *QueryIdentityByNationalIdRequest, opts ...grpc.CallOption) (*QueryIdentityByNationalIdResponse, error) {
	out := new(QueryIdentityByNationalIdResponse)
	err := c.cc.Invoke(ctx, Query_IdentityByNationalId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IdentityByOwner(ctx context.Context, in *QueryIdentityByOwnerRequest, opts ...grpc.CallOption) (*QueryIdentityByOwnerResponse, error) {
	out := new(QueryIdentityByOwnerResponse)
	err := c.cc.Invoke(ctx, Query_IdentityByOwner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Identity items.
	Identity(context.Context, *QueryGetIdentityRequest) (*QueryGetIdentityResponse, error)
	IdentityAll(context.Context, *QueryAllIdentityRequest) (*QueryAllIdentityResponse, error)
	// Queries a list of IdentityByNationalId items.
	IdentityByNationalId(context.Context, *QueryIdentityByNationalIdRequest) (*QueryIdentityByNationalIdResponse, error)
	// Queries a list of IdentityByOwner items.
	IdentityByOwner(context.Context, *QueryIdentityByOwnerRequest) (*QueryIdentityByOwnerResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Identity(context.Context, *QueryGetIdentityRequest) (*QueryGetIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identity not implemented")
}
func (UnimplementedQueryServer) IdentityAll(context.Context, *QueryAllIdentityRequest) (*QueryAllIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentityAll not implemented")
}
func (UnimplementedQueryServer) IdentityByNationalId(context.Context, *QueryIdentityByNationalIdRequest) (*QueryIdentityByNationalIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentityByNationalId not implemented")
}
func (UnimplementedQueryServer) IdentityByOwner(context.Context, *QueryIdentityByOwnerRequest) (*QueryIdentityByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentityByOwner not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Identity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Identity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Identity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Identity(ctx, req.(*QueryGetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IdentityAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IdentityAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IdentityAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IdentityAll(ctx, req.(*QueryAllIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IdentityByNationalId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentityByNationalIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IdentityByNationalId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IdentityByNationalId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IdentityByNationalId(ctx, req.(*QueryIdentityByNationalIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IdentityByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentityByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IdentityByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IdentityByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IdentityByOwner(ctx, req.(*QueryIdentityByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.identity.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Identity",
			Handler:    _Query_Identity_Handler,
		},
		{
			MethodName: "IdentityAll",
			Handler:    _Query_IdentityAll_Handler,
		},
		{
			MethodName: "IdentityByNationalId",
			Handler:    _Query_IdentityByNationalId_Handler,
		},
		{
			MethodName: "IdentityByOwner",
			Handler:    _Query_IdentityByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test/identity/query.proto",
}
